# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 467878705efb9e7c4fc9efb5d4afae122a993eeae8f8b3a08578f092e88fbe284393ee7bffecdf191bf28ee9b96d363b9647f181e7663a14b6d84bc3e9ef8b1e

test:
  secret_key_base: 7bf52998d467506a29f91067b75308e6e1e7d811a2033dafd4b098964f783a1c7b6cd2f4a18d6b56e14e1f2415f208b246d6a34fee3c6580155266b02a5cc0d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
