study_field:
  - 文系
  - 理系
  - 文理融合

gender:
  - 男
  - 女

duration:
 - 1年
 - 2年
 - 3年
 - 4年
 - 5年
 - 6年
 - 7年
 - 8年
 - 9年
 - 10年
 - 11年
 - 12年
 - 13年
 - 14年
 - 15年
 - 16年
 - 17年
 - 18年
 - その他


university:
  - 北海道大学
  - 北海道教育大学
  - 秋田大学
  - 宮城教育大学
  - 東北大学
  - 岩手大学
  - 山形大学
  - 福島大学
  - 茨城大学
  - 筑波大学
  - 筑波技術大学
  - 宇都宮大学
  - 群馬大学
  - 埼玉大学
  - 千葉大学
  - 東京大学
  - 東京医科歯科大学
  - 東京外国語大学
  - 東京学芸大学
  - 東京農工大学
  - 東京芸術大学
  - 東京工業大学
  - 東京海洋大学
  - お茶の水女子大学
  - 電気通信大学
  - 一橋大学
  - 横浜国立大学
  - 新潟大学
  - 山梨大学
  - 信州大学
  - 富山大学
  - 金沢大学
  - 福井大学
  - 岐阜大学
  - 静岡大学
  - 浜松医科大学
  - 名古屋大学
  - 滋賀大学
  - 三重大学
  - 名古屋工業大学
  - 滋賀医科大学
  - 京都大学
  - 京都教育大学
  - 神戸大学
  - 兵庫教育大学
  - 大阪教育大学
  - 大阪大学
  - 奈良教育大学
  - 奈良女子大学
  - 和歌山大学
  - 鳥取大学
  - 島根大学
  - 岡山大学
  - 広島大学
  - 山口大学
  - 徳島大学
  - 鳴門教育大学
  - 香川大学
  - 愛媛大学
  - 高知大学
  - 福岡教育大学
  - 九州工業大学
  - 佐賀大学
  - 大分大学
  - 宮崎大学
  - 熊本大学
  - 長崎大学
  - 琉球大学
  - 鹿児島大学
  - 鹿屋体育大学
  - 早稲田大学
  - 慶應義塾大学
  - 上智大学
  - 青山学院大学
  - 同志社大学
  - 法政大学
  - 関西学院大学
  - 立命館大学
  - 中央大学
  - 関西大学
  - 東京理科大学
  - 近畿大学
  - 学習院大学
  - 国際基督教大学
  - 国学院大學
  - 成蹊大学
  - 東洋大学
  - 明治学院大学
  - 成城大学
  - 駒澤大学
  - 日本大学
  - 国士舘大学
  - 芝浦工業大学
  - 東海大学
  - 愛知学院大学
  - 甲南大学
  - 名城大学
  - 京都産業大学
  - 関東学院大学
  - 東京都市大学
  - 工学院大学
  - 東洋文化大学
  - 中京大学
  - 武蔵野大学
  - 武蔵大学
  - 拓殖大学
  - 帝京平成大学
  - 神戸学院大学
  - 佛教大学
  - 東京電機大学
  - 文教大学
  - その他

faculty:
  - 経済学部
  - 経営学部
  - 商学部
  - 文学部
  - 人文学部
  - 外国語学部
  - 教育学部
  - 文化学部
  - 社会学部
  - 政策学部
  - 法学部
  - 農学部
  - 水産学部
  - 理工学部
  - 理学部
  - 工学部
  - 情報学部
  - 学芸学部
  - 音楽学部
  - 美術学部
  - 観光学部
  - 教養学部
  - 体育学部
  - 医学部
  - 看護学部
  - 歯学部
  - 薬学部
  - 心理学部
  - 獣医学部
  - 保健学部
  - 人間学部
  - 健康科学部
  - 福祉学部
  - その他

country:
  - アイスランド
  - アイルランド
  - アゼルバイジャン
  - アフガニスタン
  - アメリカ合衆国
  - アラブ首長国連邦
  - アルジェリア
  - アルゼンチン
  - アルバニア
  - アルメニア
  - アンゴラ
  - アンドラ
  - イエメン
  - イギリス
  - イスラエル
  - イタリア
  - イラク
  - イラン
  - インド
  - インドネシア
  - ウガンダ
  - ウクライナ
  - ウズベキスタン
  - ウルグアイ
  - エクアドル
  - エジプト
  - エストニア
  - エチオピア
  - エリトリア
  - オーストラリア
  - オーストリア
  - オマーン
  - オランダ
  - ガーナ
  - カーボベルデ
  - ガイアナ
  - カザフスタン
  - カタール
  - カナダ
  - ガボン
  - カメルーン
  - ガンビア
  - カンボジア
  - ギニア
  - ギニアビサウ
  - キプロス
  - キューバ
  - ギリシャ
  - キリギス
  - キルギス
  - グアテマラ
  - クウェート
  - グリーンランド
  - グルジア
  - グレナダ
  - クロアチア
  - ケニア
  - コートジボワール
  - コスタリカ
  - コロンビア
  - コンゴ共和国
  - サウジアラビア
  - サモア
  - サントメ・プリンシペ
  - ザンビア
  - サンマリノ
  - シエラレオネ
  - ジブチ
  - ジャマイカ
  - シリア
  - シンガポール
  - ジンバブエ
  - スイス
  - スウェーデン
  - スーダン
  - スペイン
  - スリナム
  - スリランカ
  - スロバキア
  - スロベニア
  - スワジランド
  - セーシェル
  - 赤道ギニア
  - セネガル
  - セントルシア
  - ソマリア
  - ソロモン諸島
  - タイ
  - 韓国
  - タジキスタン
  - タンザニア
  - チェコ
  - チャド
  - 中央アフリカ
  - 中国
  - チュニジア
  - 北朝鮮
  - チリ
  - ツバル
  - デンマーク
  - ドイツ
  - トーゴ
  - ドミニカ共和国
  - ドミニカ国
  - トリニダード・トバゴ
  - トルクメニスタン
  - トルコ
  - トンガ
  - ナイジェリア
  - ナウル
  - ナミビア
  - ニカラグア
  - ニジェール
  - 日本
  - ニュージーランド
  - ネパール
  - ノルウェー
  - バーレーン
  - ハイチ
  - パキスタン
  - バチカン市国
  - パナマ
  - バヌアツ
  - バハマ
  - パプアニューギニア
  - パラオ
  - パラグアイ
  - バルバドス
  - ハンガリー
  - バングラデシュ
  - フィジー
  - フィリピン
  - フィンランド
  - ブータン
  - ブラジル
  - フランス
  - ブルガリア
  - ブルキナファソ
  - ブルネイ
  - ブルンジ
  - ベトナム
  - ベナン
  - ベネズエラ
  - ベラルーシ
  - ベリーズ
  - ペルー
  - ベルギー
  - ポーランド
  - ボスニア・ヘルツェゴビナ
  - ボツワナ
  - ボリビア
  - ポルトガルホンジェラス
  - マーシャル諸島
  - マケドニア
  - マダガスカル
  - マラウイ
  - マリ
  - マルタ
  - マレーシア
  - ミクロネシア連邦
  - 南アフリカ
  - ミャンマー
  - メキシコ
  - モーリシャス
  - モーリタニア
  - モザンビーク
  - モナコ
  - モルディブ
  - モルドバ
  - モロッコ
  - モンゴル
  - ヨルダン
  - ラオス
  - ラトビア
  - リトアニア
  - リビア
  - リベリア
  - ルーマニア
  - ルクセンブルク
  - ルワンダ
  - レソト
  - レバノン
  - ロシア